config/routes.rb
Rails.application.routes.draw do
 
  devise_for :members
  resources :users
  # get 'home/index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
 include Pundit
 
 rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

 private

 def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
 end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_member!, except: [:index, :show]

  # GET /users or /users.json
  def index
    @users = User.all
    
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find params[:id]
  end

  # GET /users/new
  def new
    @user = User.new
    
  end

  # GET /users/1/edit
  def edit
    @user = User.find params[:id]
    
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    @user = User.find params[:id]
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user = User.find params[:id]
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :CitizenID, :login, :role, :password, :studentID, :instructorID)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'Huy Academy', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'About The App', home_about_path, class: "nav-link"  %>
        </li>
        
        <li class="nav-item">
            <%= link_to 'Users', users_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
            <%= link_to 'Add user', new_user_path, class: "nav-link"  %>
        </li>
        
        <% if member_signed_in? %>
          
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_member_session_path, method: :delete, class: "nav-link"  %>
          </li>
          
          <li class="nav-item">
            <%= link_to 'Edit Profile',  edit_member_registration_path, class: "nav-link"  %>
          </li>
        
        <% else %>
          <li class="nav-item">
              <%= link_to 'Sign Up',  new_member_registration_path, class: "nav-link"  %>
          </li>
          <li class="nav-item">
              <%= link_to 'Sign In',  new_member_session_path, class: "nav-link"  %>
          </li>
        <% end %>
        
        
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About This App</h1>
<h4>People can attend an online training course by subscribing to it. During the subscribing process, they have to specify their first name, last name, citizen ID, login, and password that they would like to use. They also have to indicate if they are students, instructors, or people outside the institute. For instructors, they have to specify the instructor ID and the department name. For students, they have to specify their student ID. During the training, the instructor of the course can divide all attendants into groups and assign a project to each group. The instructor will let the people in a group create their group name. After the project has been submitted and evaluated by the instructor, the instructor will give a score to the entire group</h4>

app/views/home/index.html.erb
<h1>Welcome to Huy Academy</h1></h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Huy Academy</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body> 
    
    <%= render 'home/header' %>
    <div class="container">
      
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      
      </br>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <br/>

  <div class="field form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :CitizenID, class:"form-control", placeholder:"CitizenID" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :login, class:"form-control", placeholder:"Login" %>
  </div>
<br/>
  <div class="field form-group">
    <%= form.select :role, ["Student", "Instructor","User"] %>
  </div>
<br/>
  <div class="field form-group">
    <%= form.text_field :password, class:"form-control", placeholder:"Password" %>
  </div>
  
  <div class="field form-group">
    <%= form.text_field :studentID, class:"form-control", placeholder:"Your ID" %>
  </div>

<br/>  
  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>
<br/>
<%= link_to 'Show', @user , class:"btn btn-dark"%> 


<%= link_to 'Back', users_path, class:"btn btn-dark" %>

app/views/users/index.html.erb
<h1>Students/Instructors List</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Citizenid</th>
      <th>Login</th>
      <th>Role</th>
      <th>Password</th>
      <th>ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.CitizenID %></td>
        <td><%= user.login %></td>
        <td><%= user.role %></td>
        <td><% user.password %></td>
        <td><%= user.studentID %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: "btn btn-dark"  %>

app/views/users/new.html.erb
<h1>New User</h1>

<br/>

<%= render 'form', user: @user , class:"btn btn-dark"  %>

<br/>

<%= link_to 'Back', users_path, class:"btn btn-dark" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
  <h1 class="display-4"><%= @user.first_name %> <%= @user.last_name %> </h1>
  <br/>
  <p class="lead">CitizenID: <%= @user.CitizenID %></p>
  <p class="lead">LoginID: <%= @user.login %></p>
  <p class="lead">Role: <%= @user.role %></p>
  <hr class="my-4">
  
  
<%= link_to 'Edit', edit_user_path(@user), class: "btn btn-dark" %> 
<%= link_to 'Back', users_path, class: "btn btn-dark" %>

</div>